### ISSUE TITLE
fit_coeff param error in WavelengthCalibration.fit()

### ISSUE THREAD

**Issue by rjs3273** [cylammarco/ASPIRED#26]
Calling  WavelengthCalibration.fit() with the optional display plot switch on is giving me an error for parameter fit_coeff. 

I think the issue is that fit_coeff does not exist as a parameter in rascal.calibrator.plot_fit(). Possibly I just have the wrong rascal? I (think I) am running the rascal dev branch.

target1D.fit(max_tries=50, stype='science+standard', display=True)

Traceback (most recent call last):
  File "/data/lt/Commissioning/SPRAT/Aspired/test_aspired_July2020.py", line 153, in <module>
    target1D.fit(max_tries=50, stype='science+standard', display=args.displayplots)
  File "/Users/rjs/miniconda3/envs/astroconda/lib/python3.6/site-packages/aspired/spectral_reduction.py", line 7115, in fit
    filename=filename)
  File "/Users/rjs/miniconda3/envs/astroconda/lib/python3.6/site-packages/aspired/spectral_reduction.py", line 4091, in fit
    filename=filename)
TypeError: plot_fit() got an unexpected keyword argument 'fit_coeff'

**Comment by rjs3273** [comment]
I retested this using the @dev branch of rascal and get the same.

**Comment by cylammarco** [comment]
A broken API in communicating with RASCAL@dev, it is now fixed.
